# Generated by Django 3.2.8 on 2021-11-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20211123_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.category'),
        ),
    ]
