# Generated by Django 3.2.8 on 2021-11-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workouts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='day',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='duration',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
